log_dir: "logs/cartpole/bc/"
load_checkpoint: null

env_type: &env_type "gym"
env_name: &env_name "CartPole-v1"
env_args: &env_args {}
observation_size: &observation_size 4
hidden_size: &hidden_size 32
action_size: &action_size 2

device_train: cpu

test_env_args:
  env_type: *env_type
  env_name: *env_name
  env_args: *env_args
  env_num: 4

policy: &policy Categorical
policy_args: {}

actor_critic_nn_type: MLP
actor_critic_nn_args:
  observation_size: *observation_size
  hidden_size: *hidden_size
  action_size: *action_size
  distribution: *policy

train_agent_args:
  optimization_params:
    learning_rate: 0.001
    gamma: 0.99
    entropy: 0.0
    clip_grad: 0.5
    gae_lambda: 0.9

  additional_params:
    loss_type: "likelihood"

demo_file: demo_files/cartpole_demo_10_ep.pickle
batch_size: 32

training_args:
  n_epoch: 6
  n_tests_per_epoch: 100
